Use pytest instead of nose
Nose is unmaintained (last release was in Jun 2015, according to
https://pypi.org/project/nose/#history), and will fail to work with
newer versions of Python:

> py3 run-test: commands[0] | nosetests
> Traceback (most recent call last):
>   File "sdx-controller/.tox/py3/bin/nosetests", line 8, in <module>
>     sys.exit(run_exit())
>   File "sdx-controller/.tox/py3/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
>     unittest.TestProgram.__init__(
>   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/main.py", line 100, in __init__
>     self.parseArgs(argv)
>   File "sdx-controller/.tox/py3/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
>     self.createTests()
>   File "sdx-controller/.tox/py3/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
>     self.test = self.testLoader.loadTestsFromNames(self.testNames)
>   File "sdx-controller/.tox/py3/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
>     return unittest.TestLoader.loadTestsFromNames(self, names, module)
>   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
>     suites = [self.loadTestsFromName(name, module) for name in names]
>   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
>     suites = [self.loadTestsFromName(name, module) for name in names]
>   File "sdx-controller/.tox/py3/lib/python3.10/site-packages/nose/loader.py", line 454, in loadTestsFromName
>     return LazySuite(
>   File "sdx-controller/.tox/py3/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
>     super(LazySuite, self).__init__()
>   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/suite.py", line 22, in __init__
>     self._tests = []
>   File "sdx-controller/.tox/py3/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
>     if isinstance(tests, collections.Callable) and not is_suite:
> AttributeError: module 'collections' has no attribute 'Callable'
> ERROR: InvocationError for command sdx-controller/.tox/py3/bin/nosetests (exited with code 1)